name: Feature request
description: Suggest an idea or enhancement for Mahi UI Component Playground
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for suggesting a new idea for Mahi UI!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem or limitation.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: How should this feature work or look?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative approaches considered
      description: Any alternative solutions or features you've looked into.
